server:
  port: 8000

spring:
  datasource:
    primary:
      url: jdbc:mysql://localhost:3308/test1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      url: jdbc:mysql://localhost:3308/test1
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver






